# Generated by Django 3.0.8 on 2021-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='unit_cost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
