# Generated by Django 3.0.8 on 2021-10-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20211015_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='options',
            new_name='combinations',
        ),
    ]
